export type Country = {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
  continent: string;
};

const flagFromCode = (code: string) =>
  code.toUpperCase().replace(/./g, c => String.fromCodePoint(127397 + c.charCodeAt(0)));

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: flagFromCode('AF'), dialCode: '+93', continent: 'Asie' },
  { code: 'ZA', name: 'Afrique du Sud', flag: flagFromCode('ZA'), dialCode: '+27', continent: 'Afrique' },
  { code: 'AL', name: 'Albanie', flag: flagFromCode('AL'), dialCode: '+355', continent: 'Europe' },
  { code: 'DZ', name: 'Algérie', flag: flagFromCode('DZ'), dialCode: '+213', continent: 'Afrique' },
  { code: 'DE', name: 'Allemagne', flag: flagFromCode('DE'), dialCode: '+49', continent: 'Europe' },
  { code: 'AD', name: 'Andorre', flag: flagFromCode('AD'), dialCode: '+376', continent: 'Europe' },
  { code: 'AO', name: 'Angola', flag: flagFromCode('AO'), dialCode: '+244', continent: 'Afrique' },
  { code: 'SA', name: 'Arabie Saoudite', flag: flagFromCode('SA'), dialCode: '+966', continent: 'Asie' },
  { code: 'AR', name: 'Argentine', flag: flagFromCode('AR'), dialCode: '+54', continent: 'Amérique du Sud' },
  { code: 'AM', name: 'Arménie', flag: flagFromCode('AM'), dialCode: '+374', continent: 'Asie' },
  { code: 'AU', name: 'Australie', flag: flagFromCode('AU'), dialCode: '+61', continent: 'Océanie' },
  { code: 'AT', name: 'Autriche', flag: flagFromCode('AT'), dialCode: '+43', continent: 'Europe' },
  { code: 'AZ', name: 'Azerbaïdjan', flag: flagFromCode('AZ'), dialCode: '+994', continent: 'Asie' },
  { code: 'BS', name: 'Bahamas', flag: flagFromCode('BS'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'BH', name: 'Bahreïn', flag: flagFromCode('BH'), dialCode: '+973', continent: 'Asie' },
  { code: 'BD', name: 'Bangladesh', flag: flagFromCode('BD'), dialCode: '+880', continent: 'Asie' },
  { code: 'BB', name: 'Barbade', flag: flagFromCode('BB'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'BY', name: 'Biélorussie', flag: flagFromCode('BY'), dialCode: '+375', continent: 'Europe' },
  { code: 'BE', name: 'Belgique', flag: flagFromCode('BE'), dialCode: '+32', continent: 'Europe' },
  { code: 'BZ', name: 'Belize', flag: flagFromCode('BZ'), dialCode: '+501', continent: 'Amérique du Nord' },
  { code: 'BJ', name: 'Bénin', flag: flagFromCode('BJ'), dialCode: '+229', continent: 'Afrique' },
  { code: 'BT', name: 'Bhoutan', flag: flagFromCode('BT'), dialCode: '+975', continent: 'Asie' },
  { code: 'BO', name: 'Bolivie', flag: flagFromCode('BO'), dialCode: '+591', continent: 'Amérique du Sud' },
  { code: 'BA', name: 'Bosnie-Herzégovine', flag: flagFromCode('BA'), dialCode: '+387', continent: 'Europe' },
  { code: 'BW', name: 'Botswana', flag: flagFromCode('BW'), dialCode: '+267', continent: 'Afrique' },
  { code: 'BR', name: 'Brésil', flag: flagFromCode('BR'), dialCode: '+55', continent: 'Amérique du Sud' },
  { code: 'BN', name: 'Brunei', flag: flagFromCode('BN'), dialCode: '+673', continent: 'Asie' },
  { code: 'BG', name: 'Bulgarie', flag: flagFromCode('BG'), dialCode: '+359', continent: 'Europe' },
  { code: 'BF', name: 'Burkina Faso', flag: flagFromCode('BF'), dialCode: '+226', continent: 'Afrique' },
  { code: 'BI', name: 'Burundi', flag: flagFromCode('BI'), dialCode: '+257', continent: 'Afrique' },
  { code: 'KH', name: 'Cambodge', flag: flagFromCode('KH'), dialCode: '+855', continent: 'Asie' },
  { code: 'CM', name: 'Cameroun', flag: flagFromCode('CM'), dialCode: '+237', continent: 'Afrique' },
  { code: 'CA', name: 'Canada', flag: flagFromCode('CA'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'CV', name: 'Cap-Vert', flag: flagFromCode('CV'), dialCode: '+238', continent: 'Afrique' },
  { code: 'CL', name: 'Chili', flag: flagFromCode('CL'), dialCode: '+56', continent: 'Amérique du Sud' },
  { code: 'CN', name: 'Chine', flag: flagFromCode('CN'), dialCode: '+86', continent: 'Asie' },
  { code: 'CY', name: 'Chypre', flag: flagFromCode('CY'), dialCode: '+357', continent: 'Europe' },
  { code: 'CO', name: 'Colombie', flag: flagFromCode('CO'), dialCode: '+57', continent: 'Amérique du Sud' },
  { code: 'KM', name: 'Comores', flag: flagFromCode('KM'), dialCode: '+269', continent: 'Afrique' },
  { code: 'CG', name: 'Congo', flag: flagFromCode('CG'), dialCode: '+242', continent: 'Afrique' },
  { code: 'CD', name: 'Congo (RDC)', flag: flagFromCode('CD'), dialCode: '+243', continent: 'Afrique' },
  { code: 'KP', name: 'Corée du Nord', flag: flagFromCode('KP'), dialCode: '+850', continent: 'Asie' },
  { code: 'KR', name: 'Corée du Sud', flag: flagFromCode('KR'), dialCode: '+82', continent: 'Asie' },
  { code: 'CR', name: 'Costa Rica', flag: flagFromCode('CR'), dialCode: '+506', continent: 'Amérique du Nord' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: flagFromCode('CI'), dialCode: '+225', continent: 'Afrique' },
  { code: 'HR', name: 'Croatie', flag: flagFromCode('HR'), dialCode: '+385', continent: 'Europe' },
  { code: 'CU', name: 'Cuba', flag: flagFromCode('CU'), dialCode: '+53', continent: 'Amérique du Nord' },
  { code: 'DK', name: 'Danemark', flag: flagFromCode('DK'), dialCode: '+45', continent: 'Europe' },
  { code: 'DJ', name: 'Djibouti', flag: flagFromCode('DJ'), dialCode: '+253', continent: 'Afrique' },
  { code: 'DO', name: 'Dominicaine (Rép.)', flag: flagFromCode('DO'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'EG', name: 'Égypte', flag: flagFromCode('EG'), dialCode: '+20', continent: 'Afrique' },
  { code: 'AE', name: 'Émirats Arabes Unis', flag: flagFromCode('AE'), dialCode: '+971', continent: 'Asie' },
  { code: 'EC', name: 'Équateur', flag: flagFromCode('EC'), dialCode: '+593', continent: 'Amérique du Sud' },
  { code: 'ER', name: 'Érythrée', flag: flagFromCode('ER'), dialCode: '+291', continent: 'Afrique' },
  { code: 'ES', name: 'Espagne', flag: flagFromCode('ES'), dialCode: '+34', continent: 'Europe' },
  { code: 'EE', name: 'Estonie', flag: flagFromCode('EE'), dialCode: '+372', continent: 'Europe' },
  { code: 'SZ', name: 'Eswatini', flag: flagFromCode('SZ'), dialCode: '+268', continent: 'Afrique' },
  { code: 'ET', name: 'Éthiopie', flag: flagFromCode('ET'), dialCode: '+251', continent: 'Afrique' },
  { code: 'FJ', name: 'Fidji', flag: flagFromCode('FJ'), dialCode: '+679', continent: 'Océanie' },
  { code: 'FI', name: 'Finlande', flag: flagFromCode('FI'), dialCode: '+358', continent: 'Europe' },
  { code: 'FR', name: 'France', flag: flagFromCode('FR'), dialCode: '+33', continent: 'Europe' },
  { code: 'GA', name: 'Gabon', flag: flagFromCode('GA'), dialCode: '+241', continent: 'Afrique' },
  { code: 'GM', name: 'Gambie', flag: flagFromCode('GM'), dialCode: '+220', continent: 'Afrique' },
  { code: 'GE', name: 'Géorgie', flag: flagFromCode('GE'), dialCode: '+995', continent: 'Asie' },
  { code: 'GH', name: 'Ghana', flag: flagFromCode('GH'), dialCode: '+233', continent: 'Afrique' },
  { code: 'GR', name: 'Grèce', flag: flagFromCode('GR'), dialCode: '+30', continent: 'Europe' },
  { code: 'GT', name: 'Guatemala', flag: flagFromCode('GT'), dialCode: '+502', continent: 'Amérique du Nord' },
  { code: 'GN', name: 'Guinée', flag: flagFromCode('GN'), dialCode: '+224', continent: 'Afrique' },
  { code: 'GQ', name: 'Guinée équatoriale', flag: flagFromCode('GQ'), dialCode: '+240', continent: 'Afrique' },
  { code: 'GW', name: 'Guinée-Bissau', flag: flagFromCode('GW'), dialCode: '+245', continent: 'Afrique' },
  { code: 'GY', name: 'Guyana', flag: flagFromCode('GY'), dialCode: '+592', continent: 'Amérique du Sud' },
  { code: 'HT', name: 'Haïti', flag: flagFromCode('HT'), dialCode: '+509', continent: 'Amérique du Nord' },
  { code: 'HN', name: 'Honduras', flag: flagFromCode('HN'), dialCode: '+504', continent: 'Amérique du Nord' },
  { code: 'HU', name: 'Hongrie', flag: flagFromCode('HU'), dialCode: '+36', continent: 'Europe' },
  { code: 'IN', name: 'Inde', flag: flagFromCode('IN'), dialCode: '+91', continent: 'Asie' },
  { code: 'ID', name: 'Indonésie', flag: flagFromCode('ID'), dialCode: '+62', continent: 'Asie' },
  { code: 'IR', name: 'Iran', flag: flagFromCode('IR'), dialCode: '+98', continent: 'Asie' },
  { code: 'IQ', name: 'Irak', flag: flagFromCode('IQ'), dialCode: '+964', continent: 'Asie' },
  { code: 'IE', name: 'Irlande', flag: flagFromCode('IE'), dialCode: '+353', continent: 'Europe' },
  { code: 'IS', name: 'Islande', flag: flagFromCode('IS'), dialCode: '+354', continent: 'Europe' },
  { code: 'IL', name: 'Israël', flag: flagFromCode('IL'), dialCode: '+972', continent: 'Asie' },
  { code: 'IT', name: 'Italie', flag: flagFromCode('IT'), dialCode: '+39', continent: 'Europe' },
  { code: 'JM', name: 'Jamaïque', flag: flagFromCode('JM'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'JP', name: 'Japon', flag: flagFromCode('JP'), dialCode: '+81', continent: 'Asie' },
  { code: 'JO', name: 'Jordanie', flag: flagFromCode('JO'), dialCode: '+962', continent: 'Asie' },
  { code: 'KZ', name: 'Kazakhstan', flag: flagFromCode('KZ'), dialCode: '+7', continent: 'Asie' },
  { code: 'KE', name: 'Kenya', flag: flagFromCode('KE'), dialCode: '+254', continent: 'Afrique' },
  { code: 'KG', name: 'Kirghizistan', flag: flagFromCode('KG'), dialCode: '+996', continent: 'Asie' },
  { code: 'KI', name: 'Kiribati', flag: flagFromCode('KI'), dialCode: '+686', continent: 'Océanie' },
  { code: 'KW', name: 'Koweït', flag: flagFromCode('KW'), dialCode: '+965', continent: 'Asie' },
  { code: 'LA', name: 'Laos', flag: flagFromCode('LA'), dialCode: '+856', continent: 'Asie' },
  { code: 'LS', name: 'Lesotho', flag: flagFromCode('LS'), dialCode: '+266', continent: 'Afrique' },
  { code: 'LV', name: 'Lettonie', flag: flagFromCode('LV'), dialCode: '+371', continent: 'Europe' },
  { code: 'LB', name: 'Liban', flag: flagFromCode('LB'), dialCode: '+961', continent: 'Asie' },
  { code: 'LR', name: 'Liberia', flag: flagFromCode('LR'), dialCode: '+231', continent: 'Afrique' },
  { code: 'LY', name: 'Libye', flag: flagFromCode('LY'), dialCode: '+218', continent: 'Afrique' },
  { code: 'LI', name: 'Liechtenstein', flag: flagFromCode('LI'), dialCode: '+423', continent: 'Europe' },
  { code: 'LT', name: 'Lituanie', flag: flagFromCode('LT'), dialCode: '+370', continent: 'Europe' },
  { code: 'LU', name: 'Luxembourg', flag: flagFromCode('LU'), dialCode: '+352', continent: 'Europe' },
  { code: 'MK', name: 'Macédoine du Nord', flag: flagFromCode('MK'), dialCode: '+389', continent: 'Europe' },
  { code: 'MG', name: 'Madagascar', flag: flagFromCode('MG'), dialCode: '+261', continent: 'Afrique' },
  { code: 'MY', name: 'Malaisie', flag: flagFromCode('MY'), dialCode: '+60', continent: 'Asie' },
  { code: 'MW', name: 'Malawi', flag: flagFromCode('MW'), dialCode: '+265', continent: 'Afrique' },
  { code: 'MV', name: 'Maldives', flag: flagFromCode('MV'), dialCode: '+960', continent: 'Asie' },
  { code: 'ML', name: 'Mali', flag: flagFromCode('ML'), dialCode: '+223', continent: 'Afrique' },
  { code: 'MT', name: 'Malte', flag: flagFromCode('MT'), dialCode: '+356', continent: 'Europe' },
  { code: 'MA', name: 'Maroc', flag: flagFromCode('MA'), dialCode: '+212', continent: 'Afrique' },
  { code: 'MH', name: 'Îles Marshall', flag: flagFromCode('MH'), dialCode: '+692', continent: 'Océanie' },
  { code: 'MR', name: 'Mauritanie', flag: flagFromCode('MR'), dialCode: '+222', continent: 'Afrique' },
  { code: 'MU', name: 'Maurice', flag: flagFromCode('MU'), dialCode: '+230', continent: 'Afrique' },
  { code: 'MX', name: 'Mexique', flag: flagFromCode('MX'), dialCode: '+52', continent: 'Amérique du Nord' },
  { code: 'FM', name: 'Micronésie', flag: flagFromCode('FM'), dialCode: '+691', continent: 'Océanie' },
  { code: 'MD', name: 'Moldavie', flag: flagFromCode('MD'), dialCode: '+373', continent: 'Europe' },
  { code: 'MC', name: 'Monaco', flag: flagFromCode('MC'), dialCode: '+377', continent: 'Europe' },
  { code: 'MN', name: 'Mongolie', flag: flagFromCode('MN'), dialCode: '+976', continent: 'Asie' },
  { code: 'ME', name: 'Monténégro', flag: flagFromCode('ME'), dialCode: '+382', continent: 'Europe' },
  { code: 'MZ', name: 'Mozambique', flag: flagFromCode('MZ'), dialCode: '+258', continent: 'Afrique' },
  { code: 'MM', name: 'Myanmar', flag: flagFromCode('MM'), dialCode: '+95', continent: 'Asie' },
  { code: 'NA', name: 'Namibie', flag: flagFromCode('NA'), dialCode: '+264', continent: 'Afrique' },
  { code: 'NR', name: 'Nauru', flag: flagFromCode('NR'), dialCode: '+674', continent: 'Océanie' },
  { code: 'NP', name: 'Népal', flag: flagFromCode('NP'), dialCode: '+977', continent: 'Asie' },
  { code: 'NI', name: 'Nicaragua', flag: flagFromCode('NI'), dialCode: '+505', continent: 'Amérique du Nord' },
  { code: 'NE', name: 'Niger', flag: flagFromCode('NE'), dialCode: '+227', continent: 'Afrique' },
  { code: 'NG', name: 'Nigéria', flag: flagFromCode('NG'), dialCode: '+234', continent: 'Afrique' },
  { code: 'NO', name: 'Norvège', flag: flagFromCode('NO'), dialCode: '+47', continent: 'Europe' },
  { code: 'NZ', name: 'Nouvelle-Zélande', flag: flagFromCode('NZ'), dialCode: '+64', continent: 'Océanie' },
  { code: 'OM', name: 'Oman', flag: flagFromCode('OM'), dialCode: '+968', continent: 'Asie' },
  { code: 'UG', name: 'Ouganda', flag: flagFromCode('UG'), dialCode: '+256', continent: 'Afrique' },
  { code: 'UZ', name: 'Ouzbékistan', flag: flagFromCode('UZ'), dialCode: '+998', continent: 'Asie' },
  { code: 'PK', name: 'Pakistan', flag: flagFromCode('PK'), dialCode: '+92', continent: 'Asie' },
  { code: 'PW', name: 'Palaos', flag: flagFromCode('PW'), dialCode: '+680', continent: 'Océanie' },
  { code: 'PS', name: 'Palestine', flag: flagFromCode('PS'), dialCode: '+970', continent: 'Asie' },
  { code: 'PA', name: 'Panama', flag: flagFromCode('PA'), dialCode: '+507', continent: 'Amérique du Nord' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: flagFromCode('PG'), dialCode: '+675', continent: 'Océanie' },
  { code: 'PY', name: 'Paraguay', flag: flagFromCode('PY'), dialCode: '+595', continent: 'Amérique du Sud' },
  { code: 'NL', name: 'Pays-Bas', flag: flagFromCode('NL'), dialCode: '+31', continent: 'Europe' },
  { code: 'PE', name: 'Pérou', flag: flagFromCode('PE'), dialCode: '+51', continent: 'Amérique du Sud' },
  { code: 'PH', name: 'Philippines', flag: flagFromCode('PH'), dialCode: '+63', continent: 'Asie' },
  { code: 'PL', name: 'Pologne', flag: flagFromCode('PL'), dialCode: '+48', continent: 'Europe' },
  { code: 'PT', name: 'Portugal', flag: flagFromCode('PT'), dialCode: '+351', continent: 'Europe' },
  { code: 'QA', name: 'Qatar', flag: flagFromCode('QA'), dialCode: '+974', continent: 'Asie' },
  { code: 'RO', name: 'Roumanie', flag: flagFromCode('RO'), dialCode: '+40', continent: 'Europe' },
  { code: 'GB', name: 'Royaume-Uni', flag: flagFromCode('GB'), dialCode: '+44', continent: 'Europe' },
  { code: 'RU', name: 'Russie', flag: flagFromCode('RU'), dialCode: '+7', continent: 'Europe' },
  { code: 'RW', name: 'Rwanda', flag: flagFromCode('RW'), dialCode: '+250', continent: 'Afrique' },
  { code: 'EH', name: 'Sahara Occidental', flag: flagFromCode('EH'), dialCode: '+212', continent: 'Afrique' },
  { code: 'SV', name: 'Salvador', flag: flagFromCode('SV'), dialCode: '+503', continent: 'Amérique du Nord' },
  { code: 'WS', name: 'Samoa', flag: flagFromCode('WS'), dialCode: '+685', continent: 'Océanie' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', flag: flagFromCode('ST'), dialCode: '+239', continent: 'Afrique' },
  { code: 'SN', name: 'Sénégal', flag: flagFromCode('SN'), dialCode: '+221', continent: 'Afrique' },
  { code: 'RS', name: 'Serbie', flag: flagFromCode('RS'), dialCode: '+381', continent: 'Europe' },
  { code: 'SC', name: 'Seychelles', flag: flagFromCode('SC'), dialCode: '+248', continent: 'Afrique' },
  { code: 'SL', name: 'Sierra Leone', flag: flagFromCode('SL'), dialCode: '+232', continent: 'Afrique' },
  { code: 'SG', name: 'Singapour', flag: flagFromCode('SG'), dialCode: '+65', continent: 'Asie' },
  { code: 'SK', name: 'Slovaquie', flag: flagFromCode('SK'), dialCode: '+421', continent: 'Europe' },
  { code: 'SI', name: 'Slovénie', flag: flagFromCode('SI'), dialCode: '+386', continent: 'Europe' },
  { code: 'SO', name: 'Somalie', flag: flagFromCode('SO'), dialCode: '+252', continent: 'Afrique' },
  { code: 'SD', name: 'Soudan', flag: flagFromCode('SD'), dialCode: '+249', continent: 'Afrique' },
  { code: 'SS', name: 'Soudan du Sud', flag: flagFromCode('SS'), dialCode: '+211', continent: 'Afrique' },
  { code: 'LK', name: 'Sri Lanka', flag: flagFromCode('LK'), dialCode: '+94', continent: 'Asie' },
  { code: 'SE', name: 'Suède', flag: flagFromCode('SE'), dialCode: '+46', continent: 'Europe' },
  { code: 'CH', name: 'Suisse', flag: flagFromCode('CH'), dialCode: '+41', continent: 'Europe' },
  { code: 'SR', name: 'Suriname', flag: flagFromCode('SR'), dialCode: '+597', continent: 'Amérique du Sud' },
  { code: 'SY', name: 'Syrie', flag: flagFromCode('SY'), dialCode: '+963', continent: 'Asie' },
  { code: 'TJ', name: 'Tadjikistan', flag: flagFromCode('TJ'), dialCode: '+992', continent: 'Asie' },
  { code: 'TZ', name: 'Tanzanie', flag: flagFromCode('TZ'), dialCode: '+255', continent: 'Afrique' },
  { code: 'TD', name: 'Tchad', flag: flagFromCode('TD'), dialCode: '+235', continent: 'Afrique' },
  { code: 'CZ', name: 'Tchéquie', flag: flagFromCode('CZ'), dialCode: '+420', continent: 'Europe' },
  { code: 'TH', name: 'Thaïlande', flag: flagFromCode('TH'), dialCode: '+66', continent: 'Asie' },
  { code: 'TL', name: 'Timor oriental', flag: flagFromCode('TL'), dialCode: '+670', continent: 'Asie' },
  { code: 'TG', name: 'Togo', flag: flagFromCode('TG'), dialCode: '+228', continent: 'Afrique' },
  { code: 'TO', name: 'Tonga', flag: flagFromCode('TO'), dialCode: '+676', continent: 'Océanie' },
  { code: 'TT', name: 'Trinité-et-Tobago', flag: flagFromCode('TT'), dialCode: '+1', continent: 'Amérique du Nord' },
  { code: 'TN', name: 'Tunisie', flag: flagFromCode('TN'), dialCode: '+216', continent: 'Afrique' },
  { code: 'TM', name: 'Turkménistan', flag: flagFromCode('TM'), dialCode: '+993', continent: 'Asie' },
  { code: 'TR', name: 'Turquie', flag: flagFromCode('TR'), dialCode: '+90', continent: 'Asie' },
  { code: 'TV', name: 'Tuvalu', flag: flagFromCode('TV'), dialCode: '+688', continent: 'Océanie' },
  { code: 'UA', name: 'Ukraine', flag: flagFromCode('UA'), dialCode: '+380', continent: 'Europe' },
  { code: 'UY', name: 'Uruguay', flag: flagFromCode('UY'), dialCode: '+598', continent: 'Amérique du Sud' },
  { code: 'VU', name: 'Vanuatu', flag: flagFromCode('VU'), dialCode: '+678', continent: 'Océanie' },
  { code: 'VA', name: 'Vatican', flag: flagFromCode('VA'), dialCode: '+379', continent: 'Europe' },
  { code: 'VE', name: 'Venezuela', flag: flagFromCode('VE'), dialCode: '+58', continent: 'Amérique du Sud' },
  { code: 'VN', name: 'Vietnam', flag: flagFromCode('VN'), dialCode: '+84', continent: 'Asie' },
  { code: 'YE', name: 'Yémen', flag: flagFromCode('YE'), dialCode: '+967', continent: 'Asie' },
  { code: 'ZM', name: 'Zambie', flag: flagFromCode('ZM'), dialCode: '+260', continent: 'Afrique' },
  { code: 'ZW', name: 'Zimbabwe', flag: flagFromCode('ZW'), dialCode: '+263', continent: 'Afrique' },
];

export const CONTINENTS = ['Afrique', 'Amérique du Nord', 'Amérique du Sud', 'Asie', 'Europe', 'Océanie'];

export const COUNTRIES_LIST = COUNTRIES;

export function getCountryByName(name: string): Country | undefined {
  return COUNTRIES.find(c => c.name === name);
}

export function getCountryFlag(name: string): string {
  return getCountryByName(name)?.flag ?? '🌍';
}

export function getCountryDialCode(name: string): string {
  return getCountryByName(name)?.dialCode ?? '';
}
