#!/usr/bin/env python3
"""Generate the idempotent France buyer migration from the verified CRM CSV.
Usage: python scripts/generate_france_prospects_migration.py /path/to/list.csv
"""
import csv,sys
from pathlib import Path
src=Path(sys.argv[1] if len(sys.argv)>1 else '../liste_5000_acheteurs_ethimarket.csv')
out=Path('supabase/migrations/20260907153000_france_5000_verified_buyers.sql')
seg={
'Restaurants et traiteurs':'restaurant','Magasins bio et épiceries':'epicerie_bio',
'Concept stores et boutiques responsables':'concept_store','Beauté naturelle et bien-être':'cosmetique',
'Mode et accessoires responsables':'mode_responsable','Grossistes, revendeurs et distributeurs':'grossiste'}
def q(v):
 v=(v or '').strip()
 return 'NULL' if not v else "'"+v.replace("'","''")+"'"
def arr(v):
 xs=[x.strip() for x in (v or '').split(';') if x.strip()]
 return 'ARRAY['+','.join(q(x) for x in xs)+']::text[]' if xs else "'{}'::text[]"
rows=list(csv.DictReader(src.open(encoding='utf-8-sig')))
head="""-- 5,000 verified French B2B buyer prospects, collected from public sources.
-- Generated by scripts/generate_france_prospects_migration.py on 2026-09-07.
-- Idempotent: external_id is stable and ON CONFLICT refreshes public profile data
-- without overwriting pipeline status, next actions or contact history.

ALTER TABLE prospects ADD COLUMN IF NOT EXISTS external_id text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS legal_name text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS siren text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS siret text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS region text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS contact_role text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS linkedin_url text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS likely_products text[] NOT NULL DEFAULT '{}';
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS legal_source_url text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS contact_source_url text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS verified_on date;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS legal_status text;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS data_origin text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_prospects_external_id ON prospects(external_id) WHERE external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prospects_region ON prospects(kind, country, region);
CREATE INDEX IF NOT EXISTS idx_prospects_siren ON prospects(siren) WHERE siren IS NOT NULL;

"""
cols="(external_id,kind,phase,segment,name,legal_name,siren,siret,city,region,country,address,contact_name,contact_role,email,phone,website,linkedin_url,likely_products,source,legal_source_url,contact_source_url,verified_on,legal_status,data_origin,status)"
chunks=[]
for i in range(0,len(rows),200):
 vals=[]
 for r in rows[i:i+200]:
  vals.append('('+','.join([
   q(r['ID prospect']),q('buyer'),'1',q(seg[r['Segment']]),q(r['Nom commercial']),q(r['Raison sociale']),q(r['SIREN']),q(r['SIRET']),
   q(r['Ville']),q(r['Région']),q('France'),q(r['Adresse professionnelle']),q(r['Nom du décideur public']),q(r['Fonction publique du décideur']),
   q(r['Email professionnel public']),q(r['Téléphone professionnel public']),q(r['Site internet']),q(r['URL LinkedIn professionnelle']),
   arr(r['Produits susceptibles de l’intéresser']),q('BANCO/OpenStreetMap + SIRENE + site officiel'),q(r['Source identité légale']),q(r['Source coordonnées publiques']),q(r['Date de vérification']),q(r['Statut SIRENE']),q(r['Type source commerce']),q('a_contacter')])+')')
 chunks.append(f"INSERT INTO prospects {cols} VALUES\n"+',\n'.join(vals)+"\nON CONFLICT (external_id) WHERE external_id IS NOT NULL DO UPDATE SET\n  segment=EXCLUDED.segment,name=EXCLUDED.name,legal_name=EXCLUDED.legal_name,siren=EXCLUDED.siren,siret=EXCLUDED.siret,city=EXCLUDED.city,region=EXCLUDED.region,address=EXCLUDED.address,contact_name=EXCLUDED.contact_name,contact_role=EXCLUDED.contact_role,email=EXCLUDED.email,phone=EXCLUDED.phone,website=EXCLUDED.website,linkedin_url=EXCLUDED.linkedin_url,likely_products=EXCLUDED.likely_products,source=EXCLUDED.source,legal_source_url=EXCLUDED.legal_source_url,contact_source_url=EXCLUDED.contact_source_url,verified_on=EXCLUDED.verified_on,legal_status=EXCLUDED.legal_status,data_origin=EXCLUDED.data_origin,updated_at=now();\n")
out.write_text(head+'\n'.join(chunks),encoding='utf-8')
print(f'wrote {out} ({len(rows)} prospects, {out.stat().st_size:,} bytes)')
