/*
# Articles du blog EthiMarket - 10 articles complets
*/
DELETE FROM articles;

INSERT INTO articles (title, slug, excerpt, category, image_url, author_name, author_avatar, published_at, read_time, featured) VALUES
  ('Rencontre avec Fatima Benali, présidente de la coopérative Argan Atlas', 'portrait-fatima-benali-argan-atlas', 'Depuis 20 ans, elle transforme la vie de 80 femmes berbères grâce à l''huile d''argan bio. Histoire d''un combat pour l''indépendance économique.', 'Portraits', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80', 'Karim Benali', 'KB', '2024-11-20', 8, true),
  ('Certification bio : le guide complet pour producteurs', 'certification-bio-guide-producteurs', 'Tout ce qu''il faut savoir pour obtenir la certification biologique : démarches, coûts, organismes, délais et pièges à éviter.', 'Agriculture', 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80', 'Marie Dupont', 'MD', '2024-11-15', 5, false),
  ('Fairtrade vs Rainforest Alliance : les différences', 'fairtrade-vs-rainforest-alliance', 'Deux labels majeurs du commerce équitable, mais des approches très différentes. Décryptage pour faire le bon choix.', 'Commerce équitable', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80', 'Sophie Martin', 'SM', '2024-11-10', 3, false),
  ('5 gestes pour réduire l''empreinte carbone en cuisine', '5-gestes-reduire-empreinte-carbone-cuisine', 'De la sélection des fournisseurs à la gestion des déchets, découvrez comment agir efficacement dans votre restaurant.', 'Environnement', 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=800&q=80', 'Sophie Martin', 'SM', '2024-11-05', 7, false),
  ('Yirgacheffe Coffee Union : 187 familles éthiopiennes', 'yirgacheffe-coffee-union-ethiopie', 'Portrait d''une coopérative emblématique qui exporte son café d''exception dans le monde entier grâce au commerce direct.', 'Portraits', 'https://images.unsplash.com/photo-1447933601403-0c6688de966e?auto=format&fit=crop&w=800&q=80', 'Karim Benali', 'KB', '2024-10-28', 6, false),
  ('Comment choisir ses fournisseurs bio en 5 étapes', 'choisir-fournisseurs-bio-5-etapes', 'Méthode pratique pour identifier, évaluer et sélectionner les meilleurs fournisseurs biologiques pour votre entreprise.', 'Guides pratiques', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80', 'Marie Dupont', 'MD', '2024-10-20', 4, false),
  ('Permaculture : révolution douce dans nos champs', 'permaculture-revolution-douce-champs', 'La permaculture gagne du terrain. Comment cette approche régénératrice transforme l''agriculture et restaure les sols.', 'Agriculture', 'https://images.unsplash.com/photo-1409172645-11033-4e9e9c7e0c7e?auto=format&fit=crop&w=800&q=80', 'Marie Dupont', 'MD', '2024-10-15', 9, false),
  ('L''agriculture bio peut-elle nourrir 10 milliards d''humains ?', 'agriculture-bio-nourrir-10-milliards', 'Étude des rendements, des coûts et des défis. La transition bio est-elle viable à l''échelle mondiale ?', 'Environnement', 'https://images.unsplash.com/photo-1574323347408-f3bfed9c5e9e?auto=format&fit=crop&w=800&q=80', 'Sophie Martin', 'SM', '2024-10-08', 10, false),
  ('Saffron Fields Iran : la renaissance du safran ancestral', 'saffron-fields-iran-renaissance-safran', 'Dans les hauts plateaux iraniens, une coopérative fait revivre la culture millénaire du safran avec des méthodes bio.', 'Portraits', 'https://images.unsplash.com/photo-1611065842937-8ea27ac07bcd?auto=format&fit=crop&w=800&q=80', 'Karim Benali', 'KB', '2024-10-01', 6, false),
  ('Négociation : obtenir les meilleurs prix bio', 'negociation-obtenir-meilleurs-prix-bio', 'Techniques et stratégies pour négocier efficacement avec vos fournisseurs bio sans sacrifier la qualité.', 'Guides pratiques', 'https://images.unsplash.com/photo-1521791136064-83865001e31c?auto=format&fit=crop&w=800&q=80', 'Marie Dupont', 'MD', '2024-09-25', 5, false);
